// <auto-generated />
using System;
using Gourmet.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gourmet.Database.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    partial class AppDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Gourmet.Database.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProductExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductPrice")
                        .HasMaxLength(10000)
                        .HasColumnType("REAL");

                    b.Property<int>("ProductQuantity")
                        .HasMaxLength(10000)
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductDescription = "This is product 1 and it has some very interesting properties.",
                            ProductExpirationDate = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "Product number 1",
                            ProductPrice = 1.0,
                            ProductQuantity = 21
                        },
                        new
                        {
                            ProductId = 2,
                            ProductDescription = "This is product 2 and it has some very interesting properties.",
                            ProductExpirationDate = new DateTime(2022, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "Product number 2",
                            ProductPrice = 2.0,
                            ProductQuantity = 22
                        },
                        new
                        {
                            ProductId = 3,
                            ProductDescription = "This is product 3 and it has some very interesting properties.",
                            ProductExpirationDate = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "Product number 3",
                            ProductPrice = 3.0,
                            ProductQuantity = 23
                        },
                        new
                        {
                            ProductId = 4,
                            ProductDescription = "This is product 4 and it has some very interesting properties.",
                            ProductExpirationDate = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "Product number 4",
                            ProductPrice = 4.0,
                            ProductQuantity = 24
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
