const BASE_URL = "https://localhost:7069/api/";
// USERS
const LOGIN = "users/login";
const SIGNUP = "users/signup";
const USER = "users/user";
const CHANGE_PASSWORD = "users/changePassword";
const CHANGE_EMAIL = "users/changeEmail";
const CHANGE_PHONE = "users/changePhone";
const GET_USER_BY_EMAIL = "getUserByEmail";
const GET_ALL_USERS = "getAllUsers";
const DELETE_USER_BY_USERNAME = "deleteUserByUsername";
// PRODUCTS
const FIND_PRODUCT_BY_ID = "findProductById";
const FIND_PRODUCT_BY_NAME = "findProductByName";
const GET_PRODUCT_PRICE = "getProductPrice";
const GET_PRODUCT_QUANTITY = "getProductQuantity";
const DECREASE_PRODUCT_QUANTITY = "decreaseProductQuantity";
const INCREASE_PRODUCT_QUANTITY = "increaseProductQuantity";
const GET_ALL_PRODUCTS = "products/getAllProducts";
// RECIPES
const FIND_RECIPE_BY_ID = "findRecipeById";
const GET_RECIPE_NAME = "getRecipeName";
const GET_RECIPE_DESCRIPTION = "getRecipeDescription";
const GET_RECIPE_PRODUCT_REFERENCE = "getRecipeProductReference";
const GET_ALL_RECIPES = "recipes/getAllRecipies";
const DELETE_RECIPE_BY_ID = "deleteRecipeById";
// OTHER
const salt = "$2a$10$CwTycUXWue0Thq9StjUM0u";
const Constants = {
  BASE_URL: BASE_URL,
  LOGIN: LOGIN,
  SIGNUP: SIGNUP,
  USER: USER,
  CHANGE_PASSWORD: CHANGE_PASSWORD,
  CHANGE_EMAIL: CHANGE_EMAIL,
  CHANGE_PHONE: CHANGE_PHONE,
  GET_USER_BY_EMAIL: GET_USER_BY_EMAIL,
  GET_ALL_USERS: GET_ALL_USERS,
  DELETE_USER_BY_USERNAME: DELETE_USER_BY_USERNAME,
  FIND_PRODUCT_BY_ID: FIND_PRODUCT_BY_ID,
  FIND_PRODUCT_BY_NAME: FIND_PRODUCT_BY_NAME,
  GET_PRODUCT_PRICE: GET_PRODUCT_PRICE,
  GET_PRODUCT_QUANTITY: GET_PRODUCT_QUANTITY,
  DECREASE_PRODUCT_QUANTITY: DECREASE_PRODUCT_QUANTITY,
  INCREASE_PRODUCT_QUANTITY: INCREASE_PRODUCT_QUANTITY,
  GET_ALL_PRODUCTS: GET_ALL_PRODUCTS,
  FIND_RECIPE_BY_ID: FIND_RECIPE_BY_ID,
  GET_RECIPE_NAME: GET_RECIPE_NAME,
  GET_RECIPE_DESCRIPTION: GET_RECIPE_DESCRIPTION,
  GET_RECIPE_PRODUCT_REFERENCE: GET_RECIPE_PRODUCT_REFERENCE,
  GET_ALL_RECIPES: GET_ALL_RECIPES,
  DELETE_RECIPE_BY_ID: DELETE_RECIPE_BY_ID,
};
export default Constants;
